/* Generated By:JJTree: Do not edit this line. ASTBasicFunctions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTBasicFunctions extends SimpleNode {
  public ASTBasicFunctions(int id) {
    super(id);
  }

  public ASTBasicFunctions(BasicParserGEN p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1356712e8ed60afbcfacf8add20eca4 (do not edit this line) */
