package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTcursorYStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTcursorYStatement extends SimpleNode {
	public int y;

	public ASTcursorYStatement(int id) {
		super(id);
	}

	public ASTcursorYStatement(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=8e1cc262bb7fd465497aae52ca639446 (do not edit this line) */
