package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTclearStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTclearStatement extends SimpleNode {
	public int start;
	public int end;

	public ASTclearStatement(int id) {
		super(id);
	}

	public ASTclearStatement(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=045b7c98eb69f702cb4ea66619de5199 (do not edit this line) */
