/* Generated By:JJTree: Do not edit this line. ASTdisplayStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTdisplayStatement extends SimpleNode {
  public ASTdisplayStatement(int id) {
    super(id);
  }

  public ASTdisplayStatement(BasicParserGEN p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=641d3c22cf41c530c030f5169a1e2f25 (do not edit this line) */
