package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTfunctionDefName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTfunctionDefName extends SimpleNode {
	public String name;

	public ASTfunctionDefName(int id) {
		super(id);
	}

	public ASTfunctionDefName(BasicParserGEN p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=1cad15000d1f916c35875464fab22b6a (do not edit this line) */
