/* Generated By:JJTree: Do not edit this line. ASTFreeBytes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTFreeBytes extends SimpleNode {
  public ASTFreeBytes(int id) {
    super(id);
  }

  public ASTFreeBytes(BasicParserGEN p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ffa1db941c4b504bd827ddea29b42e06 (do not edit this line) */
