package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTgrStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTgrStatement extends SimpleNode {
	public int background;
	public int foreground;
	public int type;

	public ASTgrStatement(int id) {
		super(id);
	}

	public ASTgrStatement(BasicParserGEN p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=56ae16a5b81e68f2d189d041402fd875 (do not edit this line) */
