package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTinitStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTinitStatement extends SimpleNode {
	public int value;

	public ASTinitStatement(int id) {
		super(id);
	}

	public ASTinitStatement(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=810d2c12b7b046215e17961a43c592fd (do not edit this line) */
