/* Generated By:JJTree: Do not edit this line. ASTKeyCharacter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTKeyCharacter extends SimpleNode {
  public ASTKeyCharacter(int id) {
    super(id);
  }

  public ASTKeyCharacter(BasicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a0596f31acf4af18f0f8636f0d62659d (do not edit this line) */
