/* Generated By:JJTree: Do not edit this line. ASTLogicalAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTLogicalAnd extends SimpleNode {
  public ASTLogicalAnd(int id) {
    super(id);
  }

  public ASTLogicalAnd(BasicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6d4420f27fc0b1213564703d72f0d1b7 (do not edit this line) */
