package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTLiteral extends SimpleNode {
	public Integer integerValue;
	public Double doubleValue;
	public String stringValue;

	public ASTLiteral(int id) {
		super(id);
	}

	public ASTLiteral(BasicParser p, int id) {
		super(p, id);
	}



	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=08a0c14673116dc561f217eaecb7c530 (do not edit this line) */
