package basicparser;
/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMult extends SimpleNode {
	public Type type;

	public ASTMult(int id) {
		super(id);
	}

	public ASTMult(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public static enum Type {
		Mul("*", "*"),
		Div("/", "/");

		private String identity;
		private String javaIdentity;

		Type(String identity, String javaIdentity) {
			this.identity = identity;
			this.javaIdentity = javaIdentity;
		}

		public String getIdentity() {
			return identity;
		}

		public String getJavaIdentity() {
			return javaIdentity;
		}

		public static Type fromIdentity(String s) {
			if(Mul.getIdentity().equals(s)) {
				return Mul;
			}
			else if(Div.getIdentity().equals(s)) {
				return Div;
			}
			throw new RuntimeException("Unknown identity " + s);
		}
	}
}
/* JavaCC - OriginalChecksum=f223a484ca72892efed0ef12d7bc3970 (do not edit this line) */
