/* Generated By:JJTree: Do not edit this line. ASTNumToStr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTNumToStr extends SimpleNode {
  public ASTNumToStr(int id) {
    super(id);
  }

  public ASTNumToStr(BasicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ba0dcbed93e48cc8d15eb9b173cd843 (do not edit this line) */
