/* Generated By:JJTree: Do not edit this line. ASTNumericExpressionParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTNumericExpressionParameter extends SimpleNode {
  public ASTNumericExpressionParameter(int id) {
    super(id);
  }

  public ASTNumericExpressionParameter(BasicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=252ab4c5f508b7276266fbc87e18d038 (do not edit this line) */
