/* Generated By:JJTree: Do not edit this line. ASTSimpleVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTSimpleVariable extends SimpleNode {
  public ASTSimpleVariable(int id) {
    super(id);
  }

  public ASTSimpleVariable(BasicParserGEN p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5880ac2419e9359ca45ddd545b01b6f3 (do not edit this line) */
