/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package basicparser;

public
class ASTUnaryExpression extends SimpleNode {

	private boolean signum = false;

	public ASTUnaryExpression(int id) {
		super(id);
	}

	public ASTUnaryExpression(BasicParserGEN p, int id) {
		super(p, id);
	}


	/** Accept the visitor. **/
	public Object jjtAccept(BasicParserGENVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public boolean isSignum() {
		return signum;
	}

	public void toggleSignum() {
		if (signum) {
			signum = false;
		}
		else {
			signum = true;
		}
	}
	
	
}
/* JavaCC - OriginalChecksum=e69c85478576d4f358906f18b258e7ee (do not edit this line) */
