/* Generated By:JJTree: Do not edit this line. ASTArray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;
import java.util.Iterator;

public
class ASTArray extends SimpleNode {

    private ArrayList<String> array = new ArrayList<String>();
    
  public ASTArray(int id) {
    super(id);
  }

  public ASTArray(BasicParser p, int id) {
    super(p, id);
  }

    public void addToken(String tok) {
	array.add(tok);
    }

    public String toString() {
	String returnString="";
	Iterator<String> alistIterator = array.iterator();
	while (alistIterator.hasNext()) {
	    returnString += "Identifier: " + alistIterator.next() + "\n";
	}
	return returnString;
    }

}
/* JavaCC - OriginalChecksum=1fdc80cf50193dd4a0677a1bff61ef65 (do not edit this line) */
