/* Generated By:JJTree: Do not edit this line. ASTdelimStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTdelimStatement extends SimpleNode {
	public int background;
	public int foreground;
	public int type;

	public ASTdelimStatement(int id) {
		super(id);
	}

	public ASTdelimStatement(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=cb906a672347fc9487360d3d9350b11c (do not edit this line) */
