/* Generated By:JJTree: Do not edit this line. ASTDimStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.util.LinkedList;

public
class ASTDimStatement extends SimpleNode {

    public LinkedList<ASTArrayDeclaration> arrayDeclarations= new LinkedList<ASTArrayDeclaration>();

  public ASTDimStatement(int id) {
    super(id);
  }

  public ASTDimStatement(BasicParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=524c5be90a209cef940a315bdb65566a (do not edit this line) */
