/* Generated By:JJTree: Do not edit this line. ASTforLoopStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTforLoopStatement extends SimpleNode {
	public int start;
	public int end;
	public int step;

	public ASTforLoopStatement(int id) {
		super(id);
	}

	public ASTforLoopStatement(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=6a891d70efe7fc3a1391d70214fccfa0 (do not edit this line) */
