/* Generated By:JJTree: Do not edit this line. ASTforLoopStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTforLoopStatement extends SimpleNode {
    
    public String toString() {
	return "lol"
    }

    public ASTforLoopStatement(int id) {
	super(id);
    }

  public ASTforLoopStatement(BasicParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19cc2e876e41118a2659724287cb9a52 (do not edit this line) */
