import programflow.MultiNumber;

/* Generated By:JJTree: Do not edit this line. ASTNumberIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTNumberIdentifier extends SimpleNode {
	public String value;

	public ASTNumberIdentifier(int id) {
		super(id);
	}

	public ASTNumberIdentifier(BasicParser p, int id) {
		super(p, id);
	}


	/**
	 * Accept the visitor. *
	 */
	public Object jjtAccept(BasicParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=00743caa46a4f21c3af38d54a968039b (do not edit this line) */
